### ISSUE TITLE
input error

### ISSUE THREAD

**Issue by WSTao** [thoughtworks-hpc/PINetTensorrt#1]
Hello, I used the source code provided by the official website to generate the model, and the operation prompts an error “Cannot find binding of given name: 0”

the nvinfer1::Dims dim = network->getInput(i)->getDimensions();
return dim.d[0]  = 1 dim.d[1] = 3 dim.d[2] = 256 it's different from input

**Comment by tw-xuwen** [comment]
> Hello, I used the source code provided by the official website to generate the model, and the operation prompts an error “Cannot find binding of given name: 0”
> 
> the nvinfer1::Dims dim = network->getInput(i)->getDimensions();
> return dim.d[0] = 1 dim.d[1] = 3 dim.d[2] = 256 it's different from input

please use Pytorch 1.0.1, and use Netron check input tensor and output tensor name and dim. can't modify the dim,  you can modify dummy input's dim when generate onnx model
