### ISSUE TITLE
result seems weird

### ISSUE THREAD

**Issue by lucasjinreal** [thoughtworks-hpc/PINetTensorrt#3]
![image](https://user-images.githubusercontent.com/21303438/97266743-f53a4e00-1863-11eb-826a-a0707903d9fa.png)

**Comment by lucasjinreal** [comment]
![image](https://user-images.githubusercontent.com/21303438/97267572-544c9280-1865-11eb-8763-5cf219ed124f.png)


OK, it's normal now, but as you can see, the red points are shifted?

**Comment by tw-xuwen** [comment]
This is the result of the third lane, not very accurate

**Comment by lucasjinreal** [comment]
@tw-xuwen  compare with python official version, it's a huge gap, not only third lane:

![image](https://user-images.githubusercontent.com/21303438/97283305-a21fc580-187a-11eb-9fe3-c4830b100831.png)

**Comment by tw-xuwen** [comment]
后面有 剔除 杂点 和 拟合部分， 这部分 后处理 代码 目前 还没 放到这个工程里。

**Comment by tw-xuwen** [comment]
the elimination and fitting, this part of post-processing code has not been put into this project. Official Python code, in some cases, the fitting quality is very poor，the lane line is seriously deformed。

**Comment by tw-xuwen** [comment]
The post-processing contains only the classified code in this project
